### ISSUE TITLE
Reactor Imposter Latest Update is Now Not Compatible with AllOfUsBot plugin.

### ISSUE THREAD

**Issue by VanillaChan6571** [XtraCube/AllOfUsBot#8]
[08:36:33 INF] Starting Impostor v0.1.0
[08:36:33 INF] Matchmaker is listening on 0.0.0.0:22023, the public server ip is no:22023.
[08:36:33 INF] Loading plugins.
[08:36:33 INF] Enabling plugin gg.xtracube.allofus AllOfUsBot (2.1.0) by XtraCube.
[08:36:33 INF] AllofUs is starting.
[08:36:33 INF] Loaded 1 plugin.
[08:36:33 INF] Application started. Press Ctrl+C to shut down.
[08:36:33 INF] Hosting environment: Production
[08:36:33 INF] Content root path: /home/container
[08:36:44 INF] KBVRJE - Player Test (1) is joining.
Unhandled exception. System.MissingMethodException: Method not found: 'Byte Impostor.Api.Net.Inner.Objects.IInnerPlayerInfo.get_ColorId()'.
   at XtraCube.Plugins.AllOfUs.Handlers.GameEventListener.SendMessage(IInnerPlayerControl player, String message)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at XtraCube.Plugins.AllOfUs.Handlers.GameEventListener.SendMessage(IInnerPlayerControl player, String message)
   at XtraCube.Plugins.AllOfUs.Handlers.GameEventListener.OnLobbyCreate(IPlayerSpawnedEvent e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
/entrypoint.sh: line 12:    13 Aborted                 (core dumped) ./Impostor.Server

**Comment by XtraCube** [comment]
I am working on making a fork of NuclearPowered/Impostor for use with AOU Bot. When it is finished, I will release it
